name: Setup Bloc Tools
description: Install the Bloc Command Line Tools

branding:
  icon: box
  color: blue

inputs:
  dart_sdk:
    description: >-
      This can be either the channel to install (i.e., 'stable', 'beta', 'dev'),
      an SDK release version (i.e., '2.19', '3.1'), or a specific SDK version
      (i.e, '2.19.1', '3.0.0-1.4.beta').
    required: false
    default: stable
  shell:
    description: The shell where you want to run the command.
    default: bash

runs:
  using: composite
  steps:
    - name: 🎯 Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: ${{inputs.dart_sdk}}

    - name: ⚙️ Setup Bloc Tools
      shell: ${{ inputs.shell }}
      run: dart pub global activate bloc_tools
