name: Setup Bloc Tools
description: Install the Bloc Command Line Tools

branding:
  icon: box
  color: blue

runs:
  using: composite
  steps:
    - name: 🎯 Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: ${{inputs.dart_sdk}}

    - name: ⚙️ Setup Bloc Tools
      shell: ${{ inputs.shell }}
      run: dart pub global activate bloc_tools
